### ISSUE TITLE
Missing stylesheet files such as `railscast.css`

### ISSUE THREAD

**Issue by wu-lee** [julianlam/nodebb-plugin-markdown#124]
I've noticed "404 not found" errors in the browser console during the loading of my NodeBB instance (v0.16.) when it uses this plugin (v8.12.4), specifically with URL paths like this:

    /plugins/nodebb-plugin-markdown/styles/railscasts.css

The filename `railscasts.css` changes to match whichever highlighting theme is selected in the markdown plugin.

I also see this in the server logs on rebuilding:

    warn: [plugins/nodebb-plugin-markdown] Mapped path 'styles => /app/code/node_modules/highlight.js/styles' not found.

So I think the styles are not in the expected place?

**Comment by julianlam** [comment]
Is this in a development instance of NodeBB w/ Markdown plugin?

**Comment by wu-lee** [comment]
Ah, no, sorry - I see mistyped the version, which should have been v1.16.0. The plug-in version is correct, however.

We're using NodeBB packaged on the Cloudron platform. (https://cloudron.io). 

There's some background information in this forum post [here][1].

[1]: https://forum.cloudron.io/topic/4250/nodebb-general-flakiness-suspected-broken-install

**Comment by julianlam** [comment]
@gramakri Does Cloudron install dependencies differently from a standard `npm` or `yarn`?

Around npm 4, I think they started flattening dependencies, and so that is why markdown now looks for `highlight.js` in `/app/code/node_modules/highlight.js` instead of `/app/code/node_modules/nodebb-plugin-markdown/node_modules/highlight.js`

This looks to be the reason for the discrepancy.

**Comment by julianlam** [comment]
Resolved in v9
