### ISSUE TITLE
List rendering of numbered lists

### ISSUE THREAD

**Issue by michael-brade** [julianlam/nodebb-plugin-markdown#125]
Hi,

are numbered lists supported? If I enter
```
1. item
2. item
3. item
```
the result is
* item
* item
* item

in the new nodebb post. **Hovever**, the NodeBB composer shows it correctly in the preview as a numbered list.

(using NodeBB 1.16.2, composer-default 6.5.5, plugin-markdown 8.12.4)

**Comment by julianlam** [comment]
Hi @michael-brade in my testing the lists are rendered correctly in the topic:

![image](https://user-images.githubusercontent.com/923011/106766536-f8359f00-6607-11eb-9192-d1f0471bfd83.png)

Are you using a different theme from vanilla/persona/material/slick?

**Comment by michael-brade** [comment]
Oh, I didn't know the theme could change that. Yes, I am using Oxide. 

Guess I'll have to fix the theme then. Thanks for the answer!

**Comment by julianlam** [comment]
:+1: Yes, looks like it is a bug with the theme. The problem is that in some themes, each post entry is an `<li>`, and so that mucks up with the browser default CSS as each bulleted/numered list thereafter is actually styled as though it were a descendant...

So each theme needs to override the bullets back to the regular style :smile:

**Comment by michael-brade** [comment]
very cool, that was exactly it! :-) Thanks :grin:
