### ISSUE TITLE
Rude checkbox selector.

### ISSUE THREAD

**Issue by yariplus** [julianlam/nodebb-plugin-markdown#88]
The plugin indiscriminately selects all checkboxes in a post, and stops other plugins from using checkboxes because it overrides the click event. Need to add a class to designate the checkbox as added by the Markdown plugin.

**Comment by julianlam** [comment]
@pauljherring @benlubar Too little too late for TDWTF, but here it is :smile:

**Comment by pauljherring** [comment]
I don't believe I've seen checkboxes used on ours...

.... 

... because they're not enabled or something?

https://what.thedailywtf.com/topic/25119/checkboxes

Raw:
![image](https://user-images.githubusercontent.com/3939886/39779407-ffdbe38a-5300-11e8-85b2-65fbdeeeeb41.png)

Live:
![image](https://user-images.githubusercontent.com/3939886/39779444-179d0cec-5301-11e8-8ca9-47044950d393.png)

**Comment by pauljherring** [comment]
Anyway, just an observation, not necessarily a bug report.

**Comment by julianlam** [comment]
I believe they're sanitized out, but some plugin you guys were using (details plugin) fell back to checkboxes as a shim in IE. This ought to fix that, even though a workaround was already put in place.

**Comment by BenLubar** [comment]
Are we using some sort of GitHub flavored markdown in NodeBB?

- [ ] Because
- [ ] that's
- [ ] what
- [ ] this
- [ ] is.

**Comment by julianlam** [comment]
Not specifically, no. We just enabled the checkbox plugin in Markdown is all :+1:
