### ISSUE TITLE
Forums in subfolder filter out relative path images not in subfolder

### ISSUE THREAD

**Issue by djensen47** [julianlam/nodebb-plugin-markdown#96]
This is a big  problem on https://www.axisandallies.org/forums

The reason is that the import plugin imported all of the posts with attachments as if the forum were not installed in a subfolder.

For instance this is what was imported: 
```
![DSCN1475.JPG](/uploads/_imported_attachments/migrated/595456_DSCN1475.JPG)
```
When it should be
```
![DSCN1475.JPG](/forums/assets/uploads/_imported_attachments/migrated/595456_DSCN1475.JPG)
```

I dug through a lot of code and ended up here in this plugin specifically these lines:
https://github.com/julianlam/nodebb-plugin-markdown/blob/5694fd8372e757d03cdcc552f736493eab0f182f/index.js#L331

It turns out that this filtering was done on purpose.

My request is to remove that restriction or at least allow it to be turned off in config.

Apparently this was added as resolution for NodeBB/NodeBB#3047 so I'm not sure if removing it would be a regression or not. I'm not even sure how this solved 3047.

**Comment by julianlam** [comment]
Hi there,

The filtering code in there resolved #3047 because uploaded images follow a very specific format (in 2015, it did, anyway)... that is, they'd be **relative** urls, and they'd be located in **/uploads**.

So I put in a simple check to comb through the image links as discovered by the markdown plugin. If it was a relative url (no hostname, 1st conditional), then it verifies that it either:

* Starts with the configured upload url
* Starts with `/uploads`

There wasn't (and more importantly, **still isn't**) any reason in a post to link out via image embed to any relative path to a folder that isn't the uploads folder, so this filtering logic keeps NodeBB safe from attacks where a malicious actor could craft a post that could DoS a forum.

**Comment by julianlam** [comment]
That said, I'll probably just add another conditional to allow imported attachments, and review the relative path logic if necessary.

**Comment by julianlam** [comment]
v8.8.5

**Comment by julianlam** [comment]
Markdown will now not filter out urls with the correct prefix but wrong relative_path structure.
